-- DROP TABLE COUNTRIES; 
-- DROP TABLE CITIES; 
-- DROP TABLE PLANTS; 



CREATE TABLE PLANTS(
	ID CHAR(3), 
	NAME VARCHAR2(25) NOT NULL,
	SCIENTIFIC_NAME VARCHAR2(30) NOT NULL, 
	CONSTRAINT PLANTIDPK PRIMARY KEY(ID)
); 

CREATE TABLE CITIES(
	ID CHAR(3),
	NAME VARCHAR2(20) NOT NULL, 
	IS_COASTAL CHAR(1),
	CONSTRAINT CITYIDPK PRIMARY KEY(ID)
); 

CREATE TABLE COUNTRIES(
	ID VARCHAR2(4), 
	NAME VARCHAR2(15) NOT NULL, 
	CAPITAL_CITY CHAR(3) NOT NULL, 
	NATIONAL_TREE CHAR(3), 
	NATIONAL_FRUIT CHAR(3),
	CONSTRAINT COUNTRYIDPK PRIMARY KEY(ID),
	CONSTRAINT CAPITAL_FK FOREIGN KEY(CAPITAL_CITY) REFERENCES CITIES(ID),
	CONSTRAINT NTREE_FK FOREIGN KEY(NATIONAL_TREE) REFERENCES PLANTS(ID),
	CONSTRAINT NFRUIT_FK FOREIGN KEY(NATIONAL_FRUIT) REFERENCES PLANTS(ID)
);


INSERT INTO PLANTS VALUES ('MNG', 'MANGO', 'Mangifera indica'); 
INSERT INTO PLANTS VALUES ('PCH', 'PEACH', 'Prunus persica'); 
INSERT INTO PLANTS VALUES ('OLV', 'OLIVE', 'Olea europaea'); 
INSERT INTO PLANTS VALUES ('BAN', 'BANYANA', 'Ficus benghalensis'); 
INSERT INTO PLANTS VALUES ('HIB', 'HIBISCUS', 'Hibiscus rosa-sinensis'); 
INSERT INTO PLANTS VALUES ('JCF', 'JACKFRUIT', 'Artocarpus heterophyllus'); 

INSERT INTO CITIES VALUES ('DHA', 'DHAKA', 'N');
INSERT INTO CITIES VALUES ('COX', 'COX''S BAZAR', 'Y'); 
INSERT INTO CITIES VALUES ('ATH', 'ATHENS', 'Y'); 
INSERT INTO CITIES VALUES ('CAN', 'CANBERRA', 'N');
INSERT INTO CITIES VALUES ('MAN', 'MANILA', 'Y'); 
INSERT INTO CITIES VALUES ('DEL', 'DELHI', 'N'); 

INSERT INTO COUNTRIES (ID, NAME, CAPITAL_CITY) VALUES ('BD', 'BANGLADESH', 'DHA');
INSERT INTO COUNTRIES (ID, NAME, CAPITAL_CITY) VALUES ('GRC', 'GREECE', 'ATH'); 
INSERT INTO COUNTRIES (ID, NAME, CAPITAL_CITY) VALUES ('PHP', 'PHILIPPINES', 'MAN'); 
INSERT INTO COUNTRIES (ID, NAME, CAPITAL_CITY) VALUES ('IND', 'INDIA', 'DEL'); 
INSERT INTO COUNTRIES (ID, NAME, CAPITAL_CITY) VALUES ('AUS', 'AUSTRALIA', 'CAN');

UPDATE COUNTRIES 
SET NATIONAL_FRUIT = 'MNG'
WHERE NAME IN ('INDIA', 'PHILIPPINES');

UPDATE COUNTRIES 
SET NATIONAL_FRUIT = 'JCF', NATIONAL_TREE = 'MNG'
WHERE NAME = 'BANGLADESH'; 

UPDATE COUNTRIES 
SET NATIONAL_TREE = 'OLV'
WHERE NAME = 'GREECE'; 

UPDATE COUNTRIES 
SET NATIONAL_TREE = 'BAN'
WHERE NAME = 'INDIA'; 

UPDATE COUNTRIES 
SET NATIONAL_FRUIT = 'PCH'
WHERE NAME = 'AUSTRALIA'; 
