-- Oracle 11g

-- CARTESIAN PRODUCT 

SELECT COUNTRIES.NAME AS COUNTRY_NAME, CITIES.NAME AS CITY_NAME  
FROM COUNTRIES, CITIES; 

-- Retrieve all the names of the countries along with the names of the capital cities 

SELECT COUNTRIES.NAME AS COUNTRY_NAME, CITIES.NAME AS CITY_NAME  
FROM COUNTRIES, CITIES
WHERE COUNTRIES.CAPITAL_CITY = CITIES.ID;

SELECT COUNTRIES.NAME AS COUNTRY_NAME, CITIES.NAME AS CITY_NAME  
FROM COUNTRIES INNER JOIN CITIES
	ON COUNTRIES.CAPITAL_CITY = CITIES.ID;
	
-- Find the national trees of the countries having a coastal city as capital  
-- Output the names of the trees, the countries, and their costal capitals   

SELECT PLANTS.NAME AS PLANT_NAME,  COUNTRIES.NAME AS COUNTRY_NAME, CITIES.NAME AS CITY_NAME  
FROM (COUNTRIES INNER JOIN CITIES
	ON COUNTRIES.CAPITAL_CITY = CITIES.ID) INNER JOIN PLANTS
	ON COUNTRIES.NATIONAL_TREE = PLANTS.ID 
WHERE CITIES.IS_COASTAL = 'Y';


SELECT PLANTS.NAME AS PLANT_NAME,  COUNTRIES.NAME AS COUNTRY_NAME, CITIES.NAME AS CITY_NAME  
FROM COUNTRIES, CITIES, PLANTS
WHERE CITIES.IS_COASTAL = 'Y' 
AND COUNTRIES.CAPITAL_CITY = CITIES.ID
AND COUNTRIES.NATIONAL_TREE = PLANTS.ID;


-- OUTER JOIN 

-- LEFT JOIN 
-- Report all the countries and scientific names of their national fruits (or null) 

SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME 
FROM COUNTRIES LEFT JOIN PLANTS 
	ON COUNTRIES.NATIONAL_FRUIT = PLANTS.ID; 
	
SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME
FROM COUNTRIES, PLANTS 
WHERE COUNTRIES.NATIONAL_FRUIT = PLANTS.ID (+); 


-- RIGHT JOIN 
-- Report all the plants in the database and mention the country they are national fruits of (or null)  

SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME 
FROM COUNTRIES RIGHT JOIN PLANTS 
	ON COUNTRIES.NATIONAL_FRUIT = PLANTS.ID; 
	
SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME
FROM COUNTRIES, PLANTS 
WHERE COUNTRIES.NATIONAL_FRUIT (+) = PLANTS.ID; 


-- FULL JOIN 
-- Report all the plants and all the countries in the database. Show if a plant is a national fruit of a country. 

SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME 
FROM COUNTRIES FULL JOIN PLANTS 
	ON COUNTRIES.NATIONAL_FRUIT = PLANTS.ID; 
	
SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME
FROM COUNTRIES, PLANTS 
WHERE COUNTRIES.NATIONAL_FRUIT (+) = PLANTS.ID
UNION
SELECT COUNTRIES.NAME, PLANTS.SCIENTIFIC_NAME
FROM COUNTRIES, PLANTS 
WHERE COUNTRIES.NATIONAL_FRUIT = PLANTS.ID (+); 
